steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  id: "npmrc-copy"
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - cf-notification
  - --entry-point=execute
  - --memory=512
  - --runtime=nodejs16
  - --source=.
  - --timeout=540s
  - --trigger-topic=mq-notification
  - --set-env-vars 
                    GMAIL_ADDRESS=$_GMAIL_ADDRESS
                    PROJECT_ID=$_PROJECT_ID
                    SENDGRID_API_KEY=$_SENDGRID_API_KEY
  waitFor: ['npmrc-copy']