steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  id: "npmrc-copy"
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - cf-notification
  - --entry-point=execute
  - --memory=512
  - --runtime=nodejs20
  - --source=.
  - --timeout=540s
  - --trigger-topic=mq-notification
  waitFor: ['npmrc-copy']