steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  id: "npmrc-copy"
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT_ID=$PROJECT_ID'
  - 'PROJECT_NUMBER=$PROJECT_NUMBER'
  - 'REV=$REVISION_ID'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - cf-notification
  - --entry-point=execute
  - --memory=512
  - --runtime=nodejs16
  - --source=.
  - --timeout=540s
  - --trigger-topic=mq-notification
  waitFor: ['npmrc-copy']