steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  id: "npmrc-copy"
- name: 'gcr.io/cloud-builders/gcloud'
env:
  - 'GMAIL_ADDRESS=$GMAIL_ADDRESS'
  - 'PROJECT_ID=$PROJECT_ID'
  - 'SENDGRID_API_KEY=$SENDGRID_API_KEY'
  args:
  - functions
  - deploy
  - cf-notification
  - --entry-point=execute
  - --memory=512
  - --runtime=nodejs16
  - --source=.
  - --timeout=540s
  - --trigger-topic=mq-notification
  waitFor: ['npmrc-copy']